[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
[rpc_endpoints]
mainnet = "${RPC}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config